"""Product model definition for the inventory domain.

This file contains the SQLModel class that represents inventory products.
"""

from __future__ import annotations

from typing import List, Optional

from sqlmodel import Field, Relationship, SQLModel


class Product(SQLModel, table=True):
	"""Database table for products.

	A product is a stockable item with quantity information and links to
	category and storage location.
	"""

	# Primary key for the product table.
	# The value is generated by SQLite when the row is inserted.
	id: Optional[int] = Field(default=None, primary_key=True)

	# Product display name used in lists, forms, and reports.
	# Indexed to support fast lookup by name.
	name: str = Field(nullable=False, index=True)

	# Current stock quantity available in inventory.
	# Defaults to zero so newly created products start with known stock.
	quantity: int = Field(default=0, nullable=False)

	# Minimum safe stock threshold used for low-stock alerts.
	# Defaults to zero and can be configured later by business users.
	min_quantity: int = Field(default=0, nullable=False)

	# Foreign key to category.id.
	# This links each product to exactly one category.
	category_id: int = Field(foreign_key="category.id", nullable=False, index=True)

	# Foreign key to location.id.
	# This links each product to exactly one storage location.
	location_id: int = Field(foreign_key="location.id", nullable=False, index=True)

	# Many-to-one relationship to Category.
	# Every product belongs to one category.
	category: Optional["Category"] = Relationship(back_populates="products")

	# Many-to-one relationship to Location.
	# Every product belongs to one location.
	location: Optional["Location"] = Relationship(back_populates="products")

	# One-to-many relationship to Movement.
	# A product can have many stock movement history records.
	movements: List["Movement"] = Relationship(back_populates="product")
