"""User model definition for the inventory domain.

This file contains the SQLModel class that represents system users.
"""

from __future__ import annotations

from typing import List, Optional

from sqlmodel import Field, Relationship, SQLModel


class User(SQLModel, table=True):
	"""Database table for application users.

	Users can perform inventory actions, and each movement is tracked against
	the responsible user for accountability.
	"""

	# Primary key for the user table.
	# Generated by the database once the user row is inserted.
	id: Optional[int] = Field(default=None, primary_key=True)

	# Unique login name used during authentication.
	# Indexed for quick lookups when users sign in.
	username: str = Field(nullable=False, index=True, unique=True)

	# Secure password representation (hash only, never plaintext password).
	# Kept as a required field to enforce secure credential storage.
	password_hash: str = Field(nullable=False)

	# Role name used for authorization decisions (for example, "admin").
	# Stored as text to keep role management simple and flexible.
	role: str = Field(nullable=False, index=True)

	# One-to-many relationship:
	# one user can create many movement records.
	movements: List["Movement"] = Relationship(back_populates="user")
